### ISSUE TITLE
Routerを使えるようにする

### ISSUE THREAD

**Issue by junya-shimada** [JunyaLab/secretary#1]
## Background：背景
reactでアプリを作成するときは、ページの遷移のために ' router ' を使用する。

## AsIs：現状
routerが使えず、画面の遷移がしづらい。

## ToBe：目指すところ
routerを使用できるように雛形を準備する。

## Todo：やること
- [x] Terminalで、 ' npm install --save react-router-dom ' を実行
- [x] 遷移のために<Link>タグを含んだコンポーネントを２つ以上用意
- [x] App.jsを編集して、Routesを使用する書き方で(v6)、routerの準備を完了
